services:
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth_service/dockerfile
    container_name: auth-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth_service/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/auth_db

  chatbot-service:
    build:
      context: .
      dockerfile: ./services/chatbot_service/dockerfile
    container_name: chatbot-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    volumes:
      - ./services/chatbot_service/app:/app/app
      - ./shared:/app/shared
    environment:
      - OPENAI_API_KEY=your-openai-key

  conversation-service:
    build:
      context: .
      dockerfile: ./services/conversation_service/dockerfile
    container_name: conversation-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    volumes:
      - ./services/conversation_service/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - postgres
      - redis
      - chromadb
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/convo_db
      - REDIS_URL=redis://redis:6379
      - CHROMA_DB_URL=http://chromadb:8000

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api_gateway/dockerfile
    container_name: api-gateway
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./services/api_gateway/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - auth-service
      - chatbot-service
      - conversation-service

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
          - ./services/postgres-init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    volumes:
      - chroma_data:/chroma/.chroma/index
    ports:
      - "8004:8000"

volumes:
  postgres_data:
  chroma_data:
