version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth_service/dockerfile
    container_name: auth-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./services/auth_service/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/auth_db
    expose:
      - "8001"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  chatbot-service:
    build:
      context: .
      dockerfile: ./services/chatbot_service/dockerfile
    container_name: chatbot-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./services/chatbot_service/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - conversation-service
    environment:
      - GEMINI_API_KEY=AIzaSyAMOb7GiwTi_P2nv9X6kUvroKifPwhMTeY
      - GEMINI_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
      - CONVERSATION_SERVICE_URL=http://conversation-service:8003
    expose:
      - "8002"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  conversation-service:
    build:
      context: .
      dockerfile: ./services/conversation_service/dockerfile
    container_name: conversation-service
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    volumes:
      - ./services/conversation_service/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - postgres
      - redis
      - chromadb
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/convo_db
      - REDIS_URL=redis://redis:6379
      - CHROMA_DB_URL=http://chromadb:8000
    expose:
      - "8003"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api_gateway/dockerfile
    container_name: api-gateway
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/api_gateway/app:/app/app
      - ./shared:/app/shared
    depends_on:
      - auth-service
      - chatbot-service
      - conversation-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CHATBOT_SERVICE_URL=http://chatbot-service:8002
      - CONVERSATION_SERVICE_URL=http://conversation-service:8003
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./services/postgres-init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    expose:
      - "5432"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  redis:
    image: redis:7
    container_name: redis
    expose:
      - "6379"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    volumes:
      - chroma_data:/chroma/.chroma/index
    expose:
      - "8000"
    networks:
      - backend
    mem_limit: 512m
    cpus: 0.50

volumes:
  postgres_data:
  chroma_data:

networks:
  backend:
    driver: bridge
