# Base image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Poetry
RUN pip install --upgrade pip && pip install poetry

# Set work directory
WORKDIR /app

# Copy pyproject and install deps
COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

# Copy service code
COPY app /app/app

# Copy .env file
COPY .env /app/.env

# Expose port
EXPOSE 8001

# Run server
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
