public_paths = {
    ("GET", "/health"),
    ("GET", "/health-all"),
    ("GET", "/openapi.json"),
    ("GET", "/auth/health"),
    ("GET", "/auth/health-all"),
    ("GET", "/auth/me"),
    ("GET", "/auth/openapi.json"),
    ("POST", "/auth/login"),
    ("POST", "/auth/refresh"),
    ("POST", "/auth/register"),
    ("POST", "/auth/forgot-password"),
    ("POST", "/auth/reset-password"),
    ("GET", "/chatbot/health"),
    ("GET", "/chatbot/health-all"),
    ("GET", "/chatbot/openapi.json"),
    ("GET", "/conversation/health"),
    ("GET", "/conversation/health-all"),
    ("GET", "/conversation/openapi.json"),
}
